const moveNames = [
  "I Don't Know The Name For This",
  "Advantage Awarded",
  "Severe Foul",
  "Serious Foul",
  "Combatitiveness Foul; Stalling; Fleeing",
  "Disqualification",
  "Penalty",
  "Deduction",
  "Win",
  "Tie; Draw",
  "Match Start",
  "Possible Mistake in Awarding Points",
  "Match End",
  "Overtime",
  "Pause",
  "Video Pause Or Freeze",
  "X Pass",
  "Leg Drag",
  "Knee Slice",
  "Back Step",
  "Over Under Pass",
  "Double Under Pass",
  "Toreando Pass",
  "Guard Pass from Berimbolo or Inverted Position",
  "Leg Weave Pass",
  "Cartwheel Pass",
  "Body Lock Pass",
  "Rapid Combination Of Different Passes",
  "Standing Guard Pass",
  "Kimura Trap Pass",
  "Back Mount",
  "Back Control",
  "Mount",
  "Knee on Belly",
  "Z Guard",
  "Truck",
  "Butterfly Guard",
  "North South",
  "Standing Guard Break",
  "X Guard",
  "Single-leg X Guard",
  "Leg lasso",
  "Guard Jump",
  "Guard Pull",
  "Half-Guard Pull",
  "Half-Guard",
  "Pitstop",
  "Spider Guard",
  "New York",
  "Crackhead Control",
  "Stoner Control",
  "Electric Chair",
  "Kesa Gatame; Scarf Hold",
  "Head and Arm",
  "Reverse Cowgirl",
  "Turtle; Quarters",
  "Berimbolo",
  "De La Riva Guard",
  "Donkey Guard",
  "Squid Guard",
  "Koala Guard",
  "50/50",
  "Outside Ashi Garami",
  "4/11; Honey Hole; The Saddle; Inside Sankaku",
  "Worm Guard",
  "Crab Ride",
  "Elbow-knee Escape",
  "Reverse De la Riva",
  "Sprawl",
  "Back Escape",
  "4/11; Honey Hole; The Saddle; Inside Sankaku Escape",
  "Heel Hook Escape",
  "Body Slam",
  "Pass To Half Guard",
  "Williams Guard",
  "Clamp Guard",
  "Standing Guard Open",
  "Body Triangle",
  "Body Triangle Escape",
  "Crucifix",
  "Crucifix Escape",
  "Cross-sides Escape/Side Control Escape",
  "Guard Retention",
  "Armbar Escape",
  "Clinch",
  "Standing Up",
  "Take Down Defense",
  "Sit",
  "Grip Break",
  "Head Control Or Clinch",
  "Foot Stomp",
  "Waiter Entanglement",
  "Closed Guard",
  "Opening Of Closed Guard",
  "Deep Half Guard",
  "Posts On Own Leg To Prevent Pass",
  "Prevent Opponent From Taking Top",
  "Diesel Squeezel",
  "Bow and Arrow",
  "Cross Collar Choke",
  "Baseball Bat Choke",
  "Clock Choke",
  "Hail Mary; Clark Gracie Choke",
  "Von Flue (Preux) Choke",
  "Peruvian Necktie",
  "Japanese Necktie",
  "Spin Choke",
  "Rodeo Choke",
  "Ezekiel",
  "North South Choke (gi or nogi); Munson choke",
  "Anaconda",
  "D'arce; Brabo",
  "Guillotine",
  "Arm-In Guillotine",
  "Paper Cutter",
  "Loop Choke",
  "Can Opener",
  "Arm Triangle",
  "Triangle",
  "Rear Naked Choke",
  "Jumping Triangle",
  "Arm Bar or Straight Arm Lock",
  "Biceps Slicer",
  "Dead Orchard",
  "Americana; Keylock; Paintbrush",
  "Kimura",
  "Omoplata",
  "Baratoplata",
  "Monoplata",
  "Knee Bar",
  "Inside Heel Hook",
  "Toe Hold/Figure 4 Toe Hold",
  "Outside Heel Hook",
  "Calf Slicer",
  "Twister; Wrestler’s Guillotine",
  "Ankle Lock",
  "Texas Cloverleaf",
  "Banana Split",
  "Wrist Lock",
  "Verbal Tap",
  "Scissor Sweep",
  "Flower Sweep",
  "Old School Sweep",
  "Simple Sweep",
  "Hip Bump Sweep",
  "Schoolyard Sweep",
  "Lumberjack Sweep",
  "Lasso Sweep",
  "Butterfly Sweep",
  "Elevator Sweep",
  "Plan B Sweep",
  "Sickle Sweep",
  "Sweep from Omoplata",
  "Sit up sweep; Reversal",
  "Marcelo Sweep",
  "Waiter Sweep",
  "Arm Drag",
  "X Guard Sweep",
  "Sweep From Deep Half Guard",
  "Upa Sweet",
  "Knee Drop Ogoshi; Knee Drop",
  "Single Leg",
  "High Single",
  "Double Leg",
  "Ankle Pick",
  "Scissor Takedown",
  "Suplex",
  "Deashi Harai; Forward Foot Sweep",
  "Hiza Guruma; Knee Wheel",
  "Sasae Tsurikomi Ashi; Lifting Pulling Ankle Block",
  "Uki Goshi; Floating Hip",
  "Osoto Gari; Large Outer Reaping",
  "O Goshi; Large Hip Throw",
  "Ouchi Gari; Large Inner Reaping",
  "Seoi Nage; Two Arm Shoulder Throw",
  "Kosoto Gari; Small Outside Reap",
  "Kouchi Gari; Small Inner Reap",
  "Koshi Guruma; Hip Wheel",
  "Tsurikomi Goshi; Lifting Pulling Hip",
  "Okuriashi Harai; Following Foot Sweep",
  "Tai Otoshi; Body Drop",
  "Harai Goshi; Sweeping Hip Throw",
  "Uchi Mata",
  "Kosoto Gake; Small Outside Hook",
  "Tsuri Goshi; Lifting Hip",
  "Yoko Otoshi; Side Drop",
  "Ashi Guruma; Leg Wheel",
  "Hane Goshi; Spring Hip Throw",
  "Harai Tsurikomi Ashi;Lifting Pulling Foot Sweep",
  "Tomoe Nage; Circle Throw",
  "Kata Guruma; Shoulder Wheel",
  "Sumi Gaeshi; Corner Reversal",
  "Tani Otoshi; Valley Drop",
  "Hane Makikomi; Spring Wrap-around Throw",
  "Sukui Nage; Scoop Throw",
  "Utsuri Goshi; Changing Hip Throw",
  "O Guruma; Large Wheel",
  "Soto Makikomi; Outer Wrap Around",
  "Uki Otoshi; Floating Drop",
  "Osoto Guruma; Large Outer Wheel",
  "Uki Waza; Floating Technique",
  "Yoko Wakare; Side Separation",
  "Yoko Guruma; Side Wheel",
  "Ushiro Goshi; Rear Hip Throw",
  "Ura Nage; Rear Throw",
  "Sumi Otoshi; Corner Drop",
  "Yoko Gake; Side Hook",
  "Obi Otoshi; Belt Drop",
  "Seoi Otoshi",
  "Yama Arashi; Mountain Storm",
  "Osoto Otoshi; Large Outer Drop",
  "Daki Wakare; High Lift and Separate",
  "Hikikomi Gaeshi; Pulling-in Reversal",
  "Tawara Gaeshi; Rice Bale Reversal",
  "Uchi Makikomi; Inner Wraparound",
  "Morote Gari; Two Hand Reap",
  "Kibisu Gaeshi",
  "Daki Age; High Lift",
  "Kouchi Gaeshi",
  "Osoto Gaeshi",
  "Uchi Mata Gaeshi",
  "Kani Basami; Flying Scissors",
  "Kawazu Gake",
  "Uchi Mata Makikomi; Inner Thigh Wrap Around",
  "Ippon Seoinage; One Arm Shoulder Throw",
  "Kuchiki Taoshi",
  "Uchi Mata Sukashi",
  "Tsubame Gaeshi; Swallow’s Flight Reversal",
  "Ouchi Gaeshi",
  "Harai Goshi Gaeshi",
  "Hane Goshi Gaeshi",
  "Osoto Makikomi; Major O uter Wrap Around",
  "Harai Makikomi; Sweeping Wraparound",
  "Sode Tsurikomi Goshi; Sleeve Lifting Pulling Hip",
  "Bear Hug",
  "Not Sure",
  "Kari-ashi",
  "Hip Toss",
  "Knee Tap",
  "High Dive",
];

export default moveNames;
