const moveNamesPortuguese = [
  "Kesa Gatame",
  "Berimbolo",
  "Mata Leao",
  "De La Riva",
  "50/50",
  "Ashi Garami",
  "Brabo",
  "Kimura",
  "Omoplata",
  "Baratoplata",
  "Monoplata",
  "Deashi Harai",
  "Hiza Guruma",
  "Sasae Tsurikomi Ashi",
  "Uki Goshi",
  "Osoto Gari",
  "O Goshi",
  "Ouchi Gari",
  "Seoi Nage",
  "Kosoto Gari",
  "Kouchi Gari",
  "Koshi Guruma",
  "Tsurikomi Goshi",
  "Okuriashi Harai",
  "Tai Otoshi",
  "Harai Goshi",
  "Uchi Mata",
  "Kosoto Gake",
  "Tsuri Goshi",
  "Yoko Otoshi",
  "Ashi Guruma",
  "Hane Goshi",
  "Harai Tsurikomi Ashi",
  "Tomoe Nage",
  "Kata Guruma",
  "Sumi Gaeshi",
  "Tani Otoshi",
  "Hane Makikomi",
  "Sukui Nage",
  "Utsuri Goshi",
  "O Guruma",
  "Soto Makikomi",
  "Uki Otoshi",
  "Osoto Guruma",
  "Uki Waza",
  "Yoko Wakare",
  "Yoko Guruma",
  "Ushiro Goshi",
  "Ura Nage",
  "Sumi Otoshi",
  "Yoko Gake",
  "Obi Otoshi",
  "Seoi Otoshi",
  "Yama Arashi",
  "Osoto Otoshi",
  "Daki Wakare",
  "Hikikomi Gaeshi",
  "Tawara Gaeshi",
  "Uchi Makikomi",
  "Morote Gari",
  "Kibisu Gaeshi",
  "Daki Age",
  "Kouchi Gaeshi",
  "Osoto Gaeshi",
  "Uchi Mata Gaeshi",
  "Kani Basami",
  "Kawazu Gake",
  "Uchi Mata Makikomi",
  "Ippon Seoinage",
  "Kuchiki Taoshi",
  "Uchi Mata Sukashi",
  "Tsubame Gaeshi",
  "Ouchi Gaeshi",
  "Harai Goshi Gaeshi",
  "Hane Goshi Gaeshi",
  "Osoto Makikomi",
  "Harai Makikomi",
  "Sode Tsurikomi Goshi",
  "Kari-ashi",
];

export default moveNamesPortuguese;
